# .readthedocs.yml

version: 2

python:
   version: 3.7
   install:
      - requirements: sphinxdocs/requirements.txt
      - method: setuptools
        path: .
   system_packages: true

sphinx:
   configuration: sphinxdocs/conf.py

